language: go

go:
  - '1.10'
  - 1.11.x
  - '1.12'

script:
  - go fmt $(go list ./...)
  - go vet $(go list ./...)
  - go test $(go list ./...)

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
